language: node_js
dist: xenial

node_js:
  - 8.12.0

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install build-essential g++

install:
  - travis_wait mvn install

script:
  - yarn test

notifications:
  email: false

before_deploy:
  - yarn run build && cp -r public/* dist

deploy:
  local_dir: dist
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
