name: Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.17.1'
      
      - name: Install and Build
        run: |
          yarn install --frozen-lockfile
          yarn test
          yarn build
