name: Build and Deploy

on:
  pull_request:  
  push:
    branches:
      - GithubActions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.17.1'
      
      - name: Install and Build
        run: |
          yarn install --frozen-lockfile
          yarn test
          yarn build
          cp -r public/* dist

      - name: Deploy
        if: ${{ github.ref == 'refs/heads/GithubActions' }}
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages-test
          FOLDER: dist
          BUILD_SCRIPT: yarn install && yarn test && yarn build
    
